# Generated by Django 2.2.4 on 2019-08-15 15:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('openbem_version', models.CharField(choices=[('10.1.0', 'v10.1.0'), ('10.1.1', 'v10.1.1')], max_length=20)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('inprogress', 'In progress'), ('test', 'Test')], default='inprogress', max_length=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
