# Generated by Django 2.2.4 on 2019-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('In progress', 'In progress'), ('Test', 'Test')], default='In progress', max_length=20),
        ),
    ]
