# Generated by Django 2.2.4 on 2019-08-22 13:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_use_status_fields_as_in_emoncms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
