# Generated by Django 2.2.4 on 2019-09-05 14:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import mhep.assessments.models.library


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[mhep.assessments.models.library.validate_dict]),
        ),
    ]
