# Generated by Django 2.2.4 on 2019-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_library_validate_data_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
