# Generated by Django 2.2.4 on 2019-09-05 17:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import mhep.assessments.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessments_allow_blank_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[mhep.assessments.validators.validate_dict]),
        ),
    ]
