# Generated by Django 2.2.4 on 2019-09-30 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0009_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
