# Generated by Django 2.2.4 on 2019-09-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_organisation_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.Organisation'),
        ),
    ]
