# Generated by Django 2.2.4 on 2019-10-03 11:05

import logging

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Assessment = apps.get_model("assessments", "Assessment")
    db_alias = schema_editor.connection.alias

    for a in Assessment.objects.filter(owner=None):
        logging.warn("\ndeleting assessment with owner=NULL: {a.name}")
        a.delete()


def reverse_func(apps, schema_editor):
    # deleted assessments can't be restored, so we do nothing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_assessments_allow_blank_owner'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='assessment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
