# Generated by Django 2.2.4 on 2019-10-07 11:19

import logging

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Library = apps.get_model("assessments", "Library")
    db_alias = schema_editor.connection.alias

    for l in Library.objects.filter(owner=None):
        logging.warn(f"\ndeleting Library with owner=NULL: {l.name}")
        l.delete()


def reverse_func(apps, schema_editor):
    # deleted assessments can't be restored, so we do nothing
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0013_assessments_owner_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
